sudo: required

services:
  - docker

env:
  DOCKER_VERSION: 1.11.1
  DOCKER_COMPOSE_VERSION: 1.6.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install docker-engine
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install: make install
script:
  - docker -v
  - docker-compose -v
  - cd web; npm test
  - cd ../api; npm test
