version: '2'
services:
  test-db:
    extends:
      file: common-services.yml
      service: db
  test-api:
    build:
      context: ./api
      dockerfile: Dockerfile.test
    links:
      - "test-db:db"
    environment:
      - ENV=TEST
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - GOOGLE_OAUTH_ID=1234
      - GOOGLE_OAUTH_SECRET=testingSecret
      - TOKEN_SECRET=testingSecret
    entrypoint: ./wait-for-it.sh db:5432 --timeout=35 -- ./entry.sh
  test-web:
    build:
      context: ./web
      dockerfile: docker/testing
    links:
      - "test-api:api"
  test-proxy:
    extends:
      file: ./common-services.yml
      service: proxy
    links:
      - "test-web:web"
      - "test-api:api"
    volumes:
      - ./proxy/nginx.dev.conf:/etc/nginx/nginx.conf:ro
